### ISSUE TITLE
driver still doesn't conform to the mainline binding

### ISSUE THREAD

**Issue by Icenowy** [yuq/linux-lima#4]
In the mainline Lima binding, the PP MMU interrupts are named ppmmuX (X from 0 to 7), but in the current driver ppXmmu is used.

See Documentation/devicetree/bindings/gpu/arm,mali-utgard.txt .

**Comment by yuq** [comment]
Right, I'll fix it latter. BTW. have you received my email before? I replied your mail but get no reply from you.

**Comment by Icenowy** [comment]
oh sorry I forgot to reply to them...

**Comment by yuq** [comment]
fixed in
https://github.com/yuq/linux-lima/commit/39b09fc69e8679adb49161a55e3d2e846a08b1fd
